Repository artefactual/atom-docs, pull requests merged in 2025-09, with the labels that each got.

#328 Add debugging documentation for Docker
  dev-manual/env/compose.rst
Labels: Community

#319 Update screenshots to bs5 for TRANSLATE
  user-manual/translate/images/globe.png
  user-manual/translate/images/languageIcon.png
  user-manual/translate/images/translateDescription.png
  user-manual/translate/images/translateInterface.png
  user-manual/translate/images/translationbar.png
Labels: user manual

#323 Add header customizations
  user-manual/administer/images/header-customizations-favicon-restore.png
  user-manual/administer/images/header-customizations-favicon-upload.png
  user-manual/administer/images/header-customizations-logo-restore.png
  user-manual/administer/images/header-customizations-logo-upload.png
  user-manual/administer/images/header-customizations-static-config.png
  user-manual/administer/settings.rst
  user-manual/administer/site-logo.rst
Labels: new content
